/* styles */
import './globals.css'
import '../../public/bootstrap-5.3.2-dist/css/bootstrap.min.css'
import { Inter } from 'next/font/google'


/* components */
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Footer/>
      </body>
    </html>
  )
}
